### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by costaoeste** [smalltide/react-native-authentication#1]
`
2016-10-23 18:46 node[1597] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-10-23 18:46 node[1597] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-10-23 18:46 node[1597] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1036:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
`

**Comment by costaoeste** [comment]
Oh! The problem was that i havent watchman installed. Now works fine.
Thanks for the sample men
